// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Tollminder.Core.ViewModels;
using Tollminder.Touch.Controllers;

namespace Tollminder.Touch
{
    public partial class CreditCardViewController : BaseViewController<CreditCardViewModel>
    {
        public CreditCardViewController() : base("CreditCardViewController", null) { }

        public CreditCardViewController(IntPtr handle) : base(handle) { }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            // Perform any additional setup after loading the view, typically from a nib.
        }
    }
}
